// <auto-generated />
using System;
using ApiVenta;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiVenta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240809024808_AddDataSeeding")]
    partial class AddDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiVenta.Entities.Codigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NoCodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Codigos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NoCodigo = "Codigo1",
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            NoCodigo = "Codigo2",
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 3,
                            NoCodigo = "Codigo3",
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 4,
                            NoCodigo = "Codigo4",
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 5,
                            NoCodigo = "Codigo5",
                            ProductoId = 3
                        });
                });

            modelBuilder.Entity("ApiVenta.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDelete")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 100,
                            DateCreate = new DateTime(2024, 8, 8, 20, 48, 8, 459, DateTimeKind.Local).AddTicks(7355),
                            DateDelete = new DateTime(2024, 8, 8, 20, 48, 8, 459, DateTimeKind.Local).AddTicks(7368),
                            Name = "Procuto1",
                            Precio = 194.34m,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 65,
                            DateCreate = new DateTime(2024, 8, 8, 20, 48, 8, 459, DateTimeKind.Local).AddTicks(7370),
                            DateDelete = new DateTime(2024, 8, 8, 20, 48, 8, 459, DateTimeKind.Local).AddTicks(7370),
                            Name = "Procuto2",
                            Precio = 56.34m,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 20,
                            DateCreate = new DateTime(2024, 8, 8, 20, 48, 8, 459, DateTimeKind.Local).AddTicks(7372),
                            DateDelete = new DateTime(2024, 8, 8, 20, 48, 8, 459, DateTimeKind.Local).AddTicks(7372),
                            Name = "Procuto3",
                            Precio = 15.34m,
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("ApiVenta.Entities.Codigo", b =>
                {
                    b.HasOne("ApiVenta.Entities.Producto", "Producto")
                        .WithMany("Codigos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApiVenta.Entities.Producto", b =>
                {
                    b.Navigation("Codigos");
                });
#pragma warning restore 612, 618
        }
    }
}
